// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace MProject.Packet
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct GPC : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static GPC GetRootAsGPC(ByteBuffer _bb) { return GetRootAsGPC(_bb, new GPC()); }
  public static GPC GetRootAsGPC(ByteBuffer _bb, GPC obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public GPC __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint UserKey { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<MProject.Packet.GPC> CreateGPC(FlatBufferBuilder builder,
      uint user_key = 0) {
    builder.StartTable(1);
    GPC.AddUserKey(builder, user_key);
    return GPC.EndGPC(builder);
  }

  public static void StartGPC(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddUserKey(FlatBufferBuilder builder, uint userKey) { builder.AddUint(0, userKey, 0); }
  public static Offset<MProject.Packet.GPC> EndGPC(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<MProject.Packet.GPC>(o);
  }
}


}
