// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace MProject.Packet
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct NC2S_UserLogout : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static NC2S_UserLogout GetRootAsNC2S_UserLogout(ByteBuffer _bb) { return GetRootAsNC2S_UserLogout(_bb, new NC2S_UserLogout()); }
  public static NC2S_UserLogout GetRootAsNC2S_UserLogout(ByteBuffer _bb, NC2S_UserLogout obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public NC2S_UserLogout __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartNC2S_UserLogout(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<MProject.Packet.NC2S_UserLogout> EndNC2S_UserLogout(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<MProject.Packet.NC2S_UserLogout>(o);
  }
}


}
