// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace MProject.Packet
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct NS2C_LeftWorld : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static NS2C_LeftWorld GetRootAsNS2C_LeftWorld(ByteBuffer _bb) { return GetRootAsNS2C_LeftWorld(_bb, new NS2C_LeftWorld()); }
  public static NS2C_LeftWorld GetRootAsNS2C_LeftWorld(ByteBuffer _bb, NS2C_LeftWorld obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public NS2C_LeftWorld __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartNS2C_LeftWorld(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<MProject.Packet.NS2C_LeftWorld> EndNS2C_LeftWorld(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<MProject.Packet.NS2C_LeftWorld>(o);
  }
}


}
