// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace MProject.Packet
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct NS2C_UserLogout : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static NS2C_UserLogout GetRootAsNS2C_UserLogout(ByteBuffer _bb) { return GetRootAsNS2C_UserLogout(_bb, new NS2C_UserLogout()); }
  public static NS2C_UserLogout GetRootAsNS2C_UserLogout(ByteBuffer _bb, NS2C_UserLogout obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public NS2C_UserLogout __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartNS2C_UserLogout(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<MProject.Packet.NS2C_UserLogout> EndNS2C_UserLogout(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<MProject.Packet.NS2C_UserLogout>(o);
  }
}


}
