// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace MProject.Packet
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct NS2C_JoinWorld : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static NS2C_JoinWorld GetRootAsNS2C_JoinWorld(ByteBuffer _bb) { return GetRootAsNS2C_JoinWorld(_bb, new NS2C_JoinWorld()); }
  public static NS2C_JoinWorld GetRootAsNS2C_JoinWorld(ByteBuffer _bb, NS2C_JoinWorld obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public NS2C_JoinWorld __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint WorldKey { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<MProject.Packet.NS2C_JoinWorld> CreateNS2C_JoinWorld(FlatBufferBuilder builder,
      uint world_key = 0) {
    builder.StartTable(1);
    NS2C_JoinWorld.AddWorldKey(builder, world_key);
    return NS2C_JoinWorld.EndNS2C_JoinWorld(builder);
  }

  public static void StartNS2C_JoinWorld(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddWorldKey(FlatBufferBuilder builder, uint worldKey) { builder.AddUint(0, worldKey, 0); }
  public static Offset<MProject.Packet.NS2C_JoinWorld> EndNS2C_JoinWorld(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<MProject.Packet.NS2C_JoinWorld>(o);
  }
}


}
