// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace MProject.Packet
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct NUserLoginPacket : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static NUserLoginPacket GetRootAsNUserLoginPacket(ByteBuffer _bb) { return GetRootAsNUserLoginPacket(_bb, new NUserLoginPacket()); }
  public static NUserLoginPacket GetRootAsNUserLoginPacket(ByteBuffer _bb, NUserLoginPacket obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public NUserLoginPacket __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartNUserLoginPacket(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<MProject.Packet.NUserLoginPacket> EndNUserLoginPacket(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<MProject.Packet.NUserLoginPacket>(o);
  }
  public static void FinishNUserLoginPacketBuffer(FlatBufferBuilder builder, Offset<MProject.Packet.NUserLoginPacket> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedNUserLoginPacketBuffer(FlatBufferBuilder builder, Offset<MProject.Packet.NUserLoginPacket> offset) { builder.FinishSizePrefixed(offset.Value); }
}


}
