// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace MProject.Packet
{

public enum Tag : uint
{
  Create = 0,
  Test = 1,
  C2S_UserLogin = 2,
  S2C_UserLogin = 3,
  C2S_UserLogout = 4,
  S2C_UserLogout = 5,
  C2S_JoinWorld = 6,
  S2C_JoinWorld = 7,
  C2S_LeftWorld = 8,
  S2C_LeftWorld = 9,
  S2C_JoinUserInWorld = 10,
  S2C_LeftUserInWorld = 11,
  C2S_MoveActorInWorld = 12,
  S2C_MoveActorInWorld = 13,
};


}
