// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace MProject.Core
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct Transform : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public Transform __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public MProject.Core.Vector3 Position { get { return (new MProject.Core.Vector3()).__assign(__p.bb_pos + 0, __p.bb); } }
  public MProject.Core.Vector3 Rotation { get { return (new MProject.Core.Vector3()).__assign(__p.bb_pos + 12, __p.bb); } }
  public MProject.Core.Vector3 Scale { get { return (new MProject.Core.Vector3()).__assign(__p.bb_pos + 24, __p.bb); } }

  public static Offset<MProject.Core.Transform> CreateTransform(FlatBufferBuilder builder, float position_X, float position_Y, float position_Z, float rotation_X, float rotation_Y, float rotation_Z, float scale_X, float scale_Y, float scale_Z) {
    builder.Prep(4, 36);
    builder.Prep(4, 12);
    builder.PutFloat(scale_Z);
    builder.PutFloat(scale_Y);
    builder.PutFloat(scale_X);
    builder.Prep(4, 12);
    builder.PutFloat(rotation_Z);
    builder.PutFloat(rotation_Y);
    builder.PutFloat(rotation_X);
    builder.Prep(4, 12);
    builder.PutFloat(position_Z);
    builder.PutFloat(position_Y);
    builder.PutFloat(position_X);
    return new Offset<MProject.Core.Transform>(builder.Offset);
  }
}


}
